global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Proxmox nodes / other hosts running node_exporter on port 9100
  - job_name: node
    static_configs:
      - targets:
          - "pve1:9100"   # pve1
          - "pve2:9100"   # pve2
          - "pve3:9100"   # pve3
          - "pve4:9100"   # pve4
          - "fiserv0:9100"
          - "lxc-plex:9100"
          - "px-u-dk-00:9100"
          - "px-u-dk-01:9100"
          - "armasrv0:9100"
          - "armasrv1:9100"
          - "armasrv2:9100"
          - "armasrv3:9100"
          
  - job_name: 'unifi-poller'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.0.0.55:9130']
      
rule_files:
  - /etc/prometheus/alerts/*.yml
